name: Deploy to PythonAnywhere

on:
  push:
    branches:
      - main  # faqat 'main' branchga push qilinganida ishga tushadi

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Kodingizni tekshirib chiqish

    - name: Reload PythonAnywhere app
      run: |
        curl -X POST \
        -H "Authorization: Token ${{ secrets.PA_API_TOKEN }}" \
        https://www.pythonanywhere.com/api/v0/user/${{ secrets.PA_USERNAME }}/webapps/${{ secrets.PA_USERNAME }}.pythonanywhere.com/reload/
